Create 'Settings' Page for Improved User Experience
wwWallet/wallet-frontend pull request #161
Opened 2024-01-24 11:43 UTC by gkatrakazas

This pull request (PR) introduces a 'Settings' page in the navigation sidebar, consolidating account-related options for enhanced user convenience. Simplifying navigation, this change ensures users can easily find and manage their preferences and account settings, improving overall usability.

2024-01-24 13:33 UTC, emlun commented on src/pages/Settings/Settings.tsx
> +							{t('common.save')}
Was the indentation change here intentional?

2024-01-24 13:33 UTC, emlun commented on src/pages/Settings/Settings.tsx
> +								{t('pageSettings.loggedPasskey.nickname')}:&nbsp;
Was the indentation change here intentional?

2024-01-24 13:34 UTC, emlun commented on src/pages/Settings/Settings.tsx
> +							</span>
The indentation of the closing tags is inconsistent here.

2024-01-24 13:35 UTC, emlun commented on src/pages/Settings/Settings.tsx
> +					{t('pageSettings.loggedPasskey.lastUsed')}:&nbsp;
Was the indentation change here intentional?

(The one below this should probably have been indented one step further already :slightly_smiling_face:)

2024-01-24 13:35 UTC, emlun commented on src/pages/Settings/Settings.tsx
> +					</>
The indentation of the `<></>` open/close tags is inconsistent here.

2024-01-24 14:57 UTC, gkatrakazas commented
Thank you for bringing this to my attention. I believe I have successfully resolved the whitespace issues with the last two commits. Please don't hesitate to inform me if you come across any other issues or concerns 😃

2024-01-26 12:42 UTC, emlun requested changes
Sorry for the delay! I spotted a few issues with the translation strings. I had to look a little closer to get the full picture, so I figured I could just fix the issues myself rather than just point them out. See meta-PR #163.

2024-01-29 10:17 UTC, emlun approved these changes

2024-01-29 11:04 UTC, merged