Session issues
wwWallet/wallet-frontend pull request #483
Opened 2024-12-03 15:06 UTC by emlun

Fixes part of #474: log out whenever `api` and `keystore` are not both logged in. This fixes the issue with `sessionStorage` attributes from the `api` module remaining after the idle logout enforced by the keystore.

2024-12-03 17:17 UTC, emlun commented
@gkatrakazas I've force-pushed over this branch with a new fix which seems to work more reliably and not log the user out immediately on signup. Please give this another go!

2024-12-03 17:56 UTC, gkatrakazas requested changes
Great work! Everything seems to function perfectly in most cases. However, I noticed one case: when a user logs in or signs up in one tab, causing another user tabs to log out, the SessionContext logout function is not triggered but on userInactivity works as expected.

2024-12-06 12:38 UTC, emlun commented
Ah, right. That was intentional because the `logout` function in `SessionContext` clears both `sessionStorage` and `localStorage`, so if user1 triggers `logout` because `user2` logged in, then the `logout` call from `user1` will immediately log `user2` out right after login. But you're right that it makes sense to also clear the `api` session when the keystore closes due to a different user logging in. Commit 95b8bed fixes this.

2024-12-06 15:53 UTC, gkatrakazas commented
The primary issue addressed in my PR (#488) was the multiple event listeners being attached to a single tab and the repeated session cleanup processes. The goal was to streamline the cleanup process to ensure it executes efficiently and consistently for every logout or session termination. Feel free to evaluate if this improves the overall cleanup process.

2024-12-06 16:34 UTC, emlun commented
Heh, interesting, I had also started on a similar refactorization I hadn't pushed :slightly_smiling_face: but with a (mostly) different goal than you had in #488. I've pushed this too as PR #489, please have a look! Maybe there's some useful overlap between these PRs.

2025-01-23 14:40 UTC, gkatrakazas commented
I think, this PR can be closed as its commits have been included in #488.

2025-01-23 14:56 UTC, emlun commented
Alright, sounds good to me. Thanks!

2025-01-23 14:56 UTC, closed without merging